import type { Metadata } from "next";
import { Suspense } from 'react'
import localFont from "next/font/local";
import { NavigationEvents } from './components/navigation-events'
import Loading from './components/loading'
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
// todo 添加meta标签
export const metadata: Metadata = {
  title: "Create Next website",
  description: "Generated by create next app",
  keywords:"first next demo"
};

export default function RootLayout({
  children,
  team,
  analytics,
}: Readonly<{
  children: React.ReactNode;
  analytics: React.ReactNode;
  team: React.ReactNode;
}>) {
  return (
    // suppressHydrationWarning 去除警告 出现警告的原因可能是浏览器的插件冲突
    //  suppressHydrationWarning={true}
    <html lang="en">
      <meta name="description" content="next.js sss" />
      <title></title>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div className="max-w-min m-auto">
          <div className="flex justify-items-center justify-around">
            <Link href="/" className="font-bold">home</Link>
            <Link href="/visitor" className="font-bold">visitor</Link>
          </div>
          <div className="flex justify-items-center w-500">
            {team}
            {analytics}
          </div>
        </div> */}
        {children}
        <Suspense fallback={<Loading/>}>
          <NavigationEvents />
        </Suspense>
      </body>
    </html>
  );
}
