// import Image from "next/image";
import type { Metadata } from "next";

// 添加meta标签
export const metadata: Metadata = {
  title: "dashboard page",
  description: "Generated by create dashboard page",
  keywords:"dashboard page"
};

export default function Page() {
  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
     dashboard page
    </div>
  );
}
